[package]
name = "widgetry"
version = "0.1.0"
edition = "2024"

[dependencies]
pollster = "0.4.0"
procfs = "0.17.0"
serde = "1.0.219"
serde_derive = "1.0.219"
toml = "0.8.20"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
wgpu = "25.0.0"
winit = "0.30.9"
